Repository boostcampwm-2024/web20-camon, pull requests merged in 2024-11, with the labels that each got.

#70 [Chore] 프로젝트 초기 설정
  .eslintignore
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/pull_request_template.md
  .gitignore
  .husky/_/husky.sh
  .husky/_/pre-commit
  .prettierrc
  README.md
  package-lock.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: :wrench: Chore

#73 [Chore] api 서버 nest 설치
  apps/api/.eslintrc.js
  apps/api/.gitignore
  apps/api/nest-cli.json
  apps/api/package.json
  apps/api/src/app.controller.spec.ts
  apps/api/src/app.controller.ts
  apps/api/src/app.module.ts
  apps/api/src/app.service.ts
  apps/api/src/main.ts
  apps/api/test/app.e2e-spec.ts
  apps/api/test/jest-e2e.json
  apps/api/tsconfig.build.json
  apps/api/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: :wrench: Chore

#78 :wrench: [Chore] 프로젝트 구조 설정
  apps/api/src/app.module.ts
  apps/api/src/attendance/attendance.module.ts
  apps/api/src/broadcast/broadcast.module.ts
  apps/api/src/common/filter/.gitkeep
  apps/api/src/common/interceptor/.gitkepp
  apps/api/src/common/pipe/.gitkeep
  apps/api/src/config/.gitkeep
  apps/api/src/member/member.module.ts
  apps/api/test/e2e/app.e2e-spec.ts
Labels: :wrench: Chore

#80 [Feat] husky로 테스트 자동 실행 설정
  .husky/_/pre-commit
  apps/api/package.json
  apps/api/test/config/jest-e2e.config.json
  apps/api/test/config/jest.config.json
  apps/api/test/jest-e2e.json
  apps/api/test/unit/app.controller.spec.ts
  package.json
Labels: :sparkles: Feat

#79 [Feat] 인터셉터 && 필터 설정
  apps/api/src/app.controller.ts
  apps/api/src/common/filter/.gitkeep
  apps/api/src/common/filter/httpException.filter.ts
  apps/api/src/common/interceptor/.gitkepp
  apps/api/src/common/interceptor/transform.interceptor.ts
  apps/api/src/common/responses/bases/successResponse.ts
  apps/api/src/common/responses/bases/successStatus.ts
  apps/api/src/common/responses/exceptions/custom.exception.ts
  apps/api/src/common/responses/exceptions/errorStatus.ts
  apps/api/src/main.ts
Labels: :sparkles: Feat

#81 [Feat] 요청/응답 로깅 설정
  .gitignore
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/common/middleware/logger.middleware.ts
  apps/api/src/config/winston.config.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat

#82 [Chore] React 프로젝트 생성 및 라이브러리 설치
  .prettierrc
  apps/api/src/app.controller.ts
  apps/api/src/common/filter/httpException.filter.ts
  apps/api/src/common/interceptor/transform.interceptor.ts
  apps/api/src/common/responses/exceptions/custom.exception.ts
  apps/api/src/main.ts
  apps/client/.eslintrc
  apps/client/.gitignore
  apps/client/README.md
  apps/client/index.html
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/postcss.config.js
  apps/client/src/App.css
  apps/client/src/App.tsx
  apps/client/src/Router.tsx
  apps/client/src/assets/fonts/PretendardVariable.woff2
  apps/client/src/index.css
  apps/client/src/main.tsx
  apps/client/src/pages/Home.tsx
  apps/client/src/pages/Profile.tsx
  apps/client/src/pages/Streaming.tsx
  apps/client/src/vite-env.d.ts
  apps/client/tailwind.config.js
  apps/client/tsconfig.app.json
  apps/client/tsconfig.json
  apps/client/tsconfig.node.json
  apps/client/vite.config.ts
  pnpm-lock.yaml
Labels: :wrench: Chore

#86 [Ci] 프론트 배포 스크립트 작성
  .github/workflows/front-deploy.yml
Labels: :globe_with_meridians: Ci

#88 [Feat]Commit 메세지 자동화
  .cz-config.js
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: :sparkles: Feat

#90 [Ci] API 서버 action 스크립트 작성 및 db 연결
  .github/workflows/api-deploy.yml
  apps/api/Dockerfile
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/config/.gitkeep
  apps/api/src/config/typeorm.config.ts
  apps/api/test/e2e/app.e2e-spec.ts
  pnpm-lock.yaml
Labels: :globe_with_meridians: Ci, BE

#91 [Feat] 체크인 버튼 UI 구현
  apps/client/.eslintrc
  apps/client/components.json
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/components/common/Header.tsx
  apps/client/src/components/ui/button.tsx
  apps/client/src/index.css
  apps/client/src/lib/utils.ts
  apps/client/tailwind.config.js
  apps/client/tsconfig.json
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#94 [Fix]: front 배포 스크립트 수정
  .github/workflows/front-deploy.yml
Labels: :bug: Fix, FE

#96 [Feat] 방송 시청 UI 구현
  apps/client/.eslintrc
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/Router.tsx
  apps/client/src/components/LivePlayer.tsx
  apps/client/src/components/icons/BlogIcon.tsx
  apps/client/src/components/icons/CloseIcon.tsx
  apps/client/src/components/icons/ExpandIcon.tsx
  apps/client/src/components/icons/MailIcon.tsx
  apps/client/src/components/icons/PauseIcon.tsx
  apps/client/src/components/icons/PlayIcon.tsx
  apps/client/src/components/icons/SoundIcon.tsx
  apps/client/src/components/icons/SoundXIcon.tsx
  apps/client/src/components/ui/select.tsx
  apps/client/src/pages/Live.tsx
  apps/client/src/pages/Streaming.tsx
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#95 [Chore] media 서버 초기 설정
  .github/workflows/media-deploy.yml
  .gitignore
  apps/api/.env.example
  apps/media/.env.example
  apps/media/.eslintrc.js
  apps/media/.gitignore
  apps/media/Dockerfile
  apps/media/nest-cli.json
  apps/media/package.json
  apps/media/src/app.controller.ts
  apps/media/src/app.module.ts
  apps/media/src/app.service.ts
  apps/media/src/common/filter/httpException.filter.ts
  apps/media/src/common/interceptor/transform.interceptor.ts
  apps/media/src/common/middleware/.gitkeep
  apps/media/src/common/pipe/.gitkeep
  apps/media/src/common/responses/bases/successResponse.ts
  apps/media/src/common/responses/bases/successStatus.ts
  apps/media/src/common/responses/exceptions/custom.exception.ts
  apps/media/src/common/responses/exceptions/errorStatus.ts
  apps/media/src/config/typeorm.config.ts
  apps/media/src/main.ts
  apps/media/src/redis.module.ts
  apps/media/test/config/jest-e2e.config.json
  apps/media/test/config/jest.config.json
  apps/media/test/e2e/app.e2e-spec.ts
  apps/media/test/unit/app.controller.spec.ts
  apps/media/tsconfig.build.json
  apps/media/tsconfig.json
  pnpm-lock.yaml
Labels: :wrench: Chore

#114 [Feat]: mediasoup 초기 설정
  apps/api/package.json
  apps/media/package.json
  apps/media/src/app.module.ts
  apps/media/src/sfu/router.gateway.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.module.ts
  apps/media/test/config/jest.config.json
  apps/media/test/e2e/app.e2e-spec.ts
  apps/media/test/unit/app.controller.spec.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#113 [Fix]: 배포 스크립트 수정
  .github/workflows/front-deploy.yml
  pnpm-lock.yaml
Labels: :bug: Fix

#98 [Chore] Chat 서버 초기 세팅
  .github/workflows/chat-deploy.yml
  apps/chat/.env.example
  apps/chat/.eslintrc.js
  apps/chat/.gitignore
  apps/chat/.prettierrc
  apps/chat/Dockerfile
  apps/chat/README.md
  apps/chat/nest-cli.json
  apps/chat/package.json
  apps/chat/src/app.controller.ts
  apps/chat/src/app.module.ts
  apps/chat/src/app.service.ts
  apps/chat/src/common/filter/webSocketExceptionFilter.ts
  apps/chat/src/common/interceptor/.gitkeep
  apps/chat/src/common/middleware/.gitkeep
  apps/chat/src/common/pipe/.gitkeep
  apps/chat/src/config/redis.config.ts
  apps/chat/src/main.ts
  apps/chat/src/redis/redis.module.ts
  apps/chat/test/config/jest-e2e.config.json
  apps/chat/test/config/jest.config.json
  apps/chat/test/e2e/app.e2e-spec.ts
  apps/chat/test/unit/app.controller.spec.ts
  apps/chat/tsconfig.build.json
  apps/chat/tsconfig.json
  pnpm-lock.yaml
Labels: :wrench: Chore

#118 [Feat]: 엔티티 생성
  apps/api/src/attendance/attendance.entity.ts
  apps/api/src/broadcast/broadcast.entity.ts
  apps/api/src/member/enum/field.enum.ts
  apps/api/src/member/member.entity.ts
  apps/api/tsconfig.json
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#115 [Feat]: roomGateway 구현
  apps/media/src/sfu/router.gateway.ts
Labels: :sparkles: Feat

#123 :sparkles: [Feat]: transport gateway 기능 구현
  apps/media/.eslintrc.js
  apps/media/src/common/responses/exceptions/errorStatus.ts
  apps/media/src/sfu/router.gateway.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/transport.gateway.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat

#124 [Feat] Producer Gateway 구현
  apps/media/src/sfu/producer/create-producer.dto.ts
  apps/media/src/sfu/producer/producer.gateway.ts
  apps/media/src/sfu/producer/producer.interface.ts
Labels: :sparkles: Feat

#128 [Refactor]: 코드 병합
  apps/media/src/sfu/consumer/consumer.gateway.ts
  apps/media/src/sfu/consumer/create-consumer.dto.ts
  apps/media/src/sfu/producer/producer.gateway.ts
  apps/media/src/sfu/router.gateway.ts
  apps/media/src/sfu/sfu.module.ts
  apps/media/src/sfu/transport.gateway.ts
Labels: :recycle: Refactor, BE

#121 [Fix] react Router v7 관련 옵션 추가
  apps/client/src/Router.tsx
Labels: :bug: Fix, FE

#131 [Fix] 프론트엔드 빌드 실패 원인 해결
  apps/client/src/components/LivePlayer.tsx
  apps/client/src/components/common/Header.tsx
  apps/client/src/components/ui/button.tsx
Labels: :bug: Fix, FE

#133 :bug: [Fix]: media서버 배포 수정
  apps/media/Dockerfile
Labels: :bug: Fix, BE

#127 [Feat] 방 생성 요청 커스텀 훅 구현
  apps/client/src/hooks/useMediasoupRoom.ts
Labels: :sparkles: Feat, FE

#132 :sparkles: [Feat]: 방송 리스트 조회 API 구현
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.entity.ts
  apps/api/src/broadcast/broadcast.module.ts
  apps/api/src/broadcast/broadcast.service.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#137 [Feat] Transport 생성 및 연결 요청 구현
  apps/client/src/hooks/useMediasoupTransport.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#138 [Refactor] sfu 서버 코드 구조 리팩토링
  apps/media/src/common/filter/webSocketException.filter.ts
  apps/media/src/common/responses/exceptions/custom-ws.exception.ts
  apps/media/src/common/responses/exceptions/errorStatus.ts
  apps/media/src/sfu/consumer/consumer.gateway.ts
  apps/media/src/sfu/dto/create-consumer.dto.ts
  apps/media/src/sfu/dto/create-producer.dto.ts
  apps/media/src/sfu/dto/create-transport.dto.ts
  apps/media/src/sfu/dto/transport-params.interface.ts
  apps/media/src/sfu/interfaces/consumer.interface.ts
  apps/media/src/sfu/interfaces/producer.interface.ts
  apps/media/src/sfu/interfaces/room-transport-info.interface.ts
  apps/media/src/sfu/producer/producer.gateway.ts
  apps/media/src/sfu/router.gateway.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.module.ts
  apps/media/src/sfu/sfu.service.ts
  apps/media/src/sfu/transport.gateway.ts
  apps/media/src/sfu/worker/worker.service.ts
Labels: :recycle: Refactor, BE

#143 [Refactor] producers 종속 범위 제한 및 filter를 이용한 에러 처리
  apps/media/src/common/filter/webSocketException.filter.ts
  apps/media/src/common/responses/exceptions/errorStatus.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
Labels: :sparkles: Feat, BE

#144 [Feat] sfu 서버 미디어 송출 중지, 방송 중단 event 등록
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
Labels: :sparkles: Feat, BE

#148 [Fix] sfu 서버 오류 수정
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
  apps/media/src/sfu/worker/worker.service.ts
Labels: :bug: Fix, BE

#146 :bug: [Fix] 환경변수 추가
  .github/workflows/front-deploy.yml
Labels: :bug: Fix, :globe_with_meridians: Ci, FE

#150 [Feat] 방송 종료, 시청 종료 이벤트 구현
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
Labels: :sparkles: Feat, BE

#153 :bug: [Fix]: Consumer 생성 로직 수정
  apps/media/src/sfu/dto/create-consumer.dto.ts
  apps/media/src/sfu/sfu.service.ts
  pnpm-lock.yaml
Labels: :bug: Fix, BE

#160 :memo: [Docs]: readme 업데이트
  README.md
Labels: :memo: Docs

#159 :bug: [Fix]: 환경변수 추가
  .github/workflows/media-deploy.yml
  apps/media/Dockerfile
  apps/media/src/sfu/sfu.service.ts
Labels: :bug: Fix, BE

#163 :sparkles: [Feat]: 방송 미리보기 카드 컴포넌트 구현
  apps/client/public/images/duck.png
  apps/client/public/images/zoom_membership_bg.png
  apps/client/src/components/LiveCard.tsx
  apps/client/src/pages/Home.tsx
  apps/client/tailwind.config.js
Labels: :sparkles: Feat, FE

#168 :bug: [Fix]: 방송 리스트 조회 응답 수정
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/broadcast/dto/broadcast-list-response.dto.ts
Labels: :bug: Fix, BE

#169 [Feat] 방송 리스트 레이아웃 UI 구현
  apps/client/src/components/LiveList.tsx
  apps/client/src/pages/Home.tsx
Labels: :sparkles: Feat, FE

#172 :bug: [Fix]: dockerfile 수정
  .github/workflows/media-deploy.yml
  apps/media/Dockerfile
Labels: :bug: Fix, :globe_with_meridians: Ci, BE

#173 [Feat] 방송 클릭 이벤트 리스너 구현
  apps/client/src/components/LiveCard.tsx
Labels: :sparkles: Feat, FE

#166 :recycle: [Refactor]: sfuService 코드 분리
  apps/media/src/common/responses/exceptions/errorStatus.ts
  apps/media/src/sfu/services/consumer.service.ts
  apps/media/src/sfu/services/producer.service.ts
  apps/media/src/sfu/services/room.service.ts
  apps/media/src/sfu/services/transport.service.ts
  apps/media/src/sfu/services/worker.service.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.module.ts
  apps/media/src/sfu/sfu.service.ts
  apps/media/src/sfu/worker/worker.service.ts
Labels: :recycle: Refactor, BE

#170 [Chore] swagger 세팅
  apps/api/package.json
  apps/api/src/app.controller.ts
  apps/api/src/common/constants/swagger-tag.enum.ts
  apps/api/src/common/decorators/error-res.decorator.ts
  apps/api/src/common/decorators/success-res.decorator.ts
  apps/api/src/config/swagger.config.ts
  apps/api/src/main.ts
  pnpm-lock.yaml
Labels: :wrench: Chore, BE

#177 [Feat] 방송 정보 제공 api 구현
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/broadcast/dto/broadcast-info-response.dto.ts
  apps/api/src/common/responses/exceptions/errorStatus.ts
Labels: :sparkles: Feat, BE

#175 [Feat] 방송 제목 변경 api 구현
  apps/api/package.json
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/broadcast/dto/update-broadcast-title.request.dto.ts
  apps/api/src/main.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#178 [Feat] 방송 중인 캠퍼의 상세 정보 UI 구현
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/components/LiveCamperInfo.tsx
  apps/client/src/components/common/IconButton.tsx
  apps/client/src/components/icons/BlogIcon.tsx
  apps/client/src/components/icons/GithubIcon.tsx
  apps/client/src/components/icons/LinkedInIcon.tsx
  apps/client/src/components/icons/MailIcon.tsx
  apps/client/src/components/ui/avatar.tsx
  apps/client/src/components/ui/badge.tsx
  apps/client/src/pages/Live.tsx
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#185 [Fix] api서버 cors 설정
  apps/api/src/main.ts
  pnpm-lock.yaml
Labels: :bug: Fix, BE

#186 [Feat] 방송 제목 수정 UI 구현
  apps/client/package.json
  apps/client/src/components/BroadcastTitle.tsx
  apps/client/src/pages/Broadcast.tsx
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#187 [Feat] 방송 리스트 조회 기능 구현
  apps/client/package.json
  apps/client/src/components/LiveList.tsx
  apps/client/src/components/common/ErrorCharacter.tsx
  apps/client/src/components/common/LoadingCharacter.tsx
  apps/client/src/env.d.ts
  apps/client/src/hooks/useAPI.ts
  apps/client/src/pages/Home.tsx
  apps/client/src/services/axios.ts
  apps/client/src/types/liveTypes.ts
  apps/client/tsconfig.json
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#189 [Feat] chat 서버 구현
  apps/chat/.prettierrc
  apps/chat/Dockerfile
  apps/chat/src/app.module.ts
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.module.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/client.ts
  apps/chat/src/chat/dto/chat.dto.ts
  apps/chat/src/chat/dto/creat-room.dto.ts
  apps/chat/src/chat/dto/join-room.dto.ts
  apps/chat/src/common/responses/exceptions/custom-ws.exception.ts
  apps/chat/src/common/responses/exceptions/errorStatus.ts
Labels: :sparkles: Feat, BE

#191 [Feat] 방송 시청 중단 시 로직 구현
  apps/client/src/hooks/useConsumer.ts
  apps/client/src/pages/Broadcast.tsx
  apps/client/src/pages/Live.tsx
Labels: :sparkles: Feat, FE

#194 [Chore] record 서버 초기 세팅
  .github/workflows/record-deploy.yml
  .gitignore
  apps/record/.env.example
  apps/record/.eslintrc.js
  apps/record/.gitignore
  apps/record/Dockerfile
  apps/record/babel.config.json
  apps/record/nodemon.json
  apps/record/package.json
  apps/record/src/index.ts
  apps/record/test/.gitkeep
  apps/record/tsconfig.json
  pnpm-lock.yaml
Labels: :wrench: Chore, BE

#142 [Feat] sfu 서비스에 API 연결
  .github/workflows/media-deploy.yml
  apps/media/src/broadcast/dto/createBroadcast.dto.ts
  apps/media/src/sfu/sfu.module.ts
  apps/media/src/sfu/sfu.service.ts
Labels: :sparkles: Feat, BE

#195 [Chore] api에 swagger 적용
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/dto/broadcast-info-response.dto.ts
  apps/api/src/broadcast/dto/broadcast-list-response.dto.ts
  apps/api/src/broadcast/dto/update-broadcast-title.request.dto.ts
Labels: :wrench: Chore, BE

#200 [Fix] 로컬 클라이언트에서 요청 시 credential 설정
  apps/client/src/hooks/useSocket.ts
  apps/client/src/services/axios.ts
Labels: :bug: Fix, FE

#199 [Feat] custom validation pipe 구현
  apps/api/src/broadcast/dto/update-broadcast-title.request.dto.ts
  apps/api/src/common/pipe/.gitkeep
  apps/api/src/common/pipe/custom-validation.pipe.ts
  apps/api/src/main.ts
  apps/chat/src/common/filter/webSocketExceptionFilter.ts
  apps/media/src/common/clients/api.client.ts
Labels: :sparkles: Feat, BE

#196 [Feat] Broadcast 종료 시, 연쇄 로직 구현
  apps/api/src/attendance/attendance.entity.ts
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.entity.ts
  apps/api/src/broadcast/broadcast.module.ts
  apps/api/src/broadcast/broadcast.service.ts
  apps/client/src/pages/Broadcast.tsx
  apps/media/src/attendance/attendance.module.ts
  apps/media/src/broadcast/broadcast.service.ts
  apps/media/src/broadcast/interfaces/broadcast-service.interface.ts
  apps/media/src/common/clients/api-client.interface.ts
  apps/media/src/common/clients/api.client.ts
  apps/media/src/sfu/services/room.service.ts
Labels: :sparkles: Feat, BE

#203 [Feat] 소켓 exception 에러 처리
  apps/client/src/hooks/useSocket.ts
  apps/client/src/pages/Broadcast.tsx
  apps/client/src/pages/Live.tsx
Labels: :sparkles: Feat, FE

#205 [Chore] 커스텀 훅 의존성 체크 로직 추가 & 타입 정리
  apps/client/src/hooks/useConsumer.ts
  apps/client/src/hooks/useProducer.ts
  apps/client/src/hooks/useRoom.ts
  apps/client/src/hooks/useTransport.ts
  apps/client/src/lib/utils.ts
  apps/client/src/pages/Broadcast.tsx
  apps/client/src/types/mediasoupTypes.ts
Labels: :wrench: Chore, FE

#208 [Feat] 방송 제목 수정 요청 구현
  apps/client/src/components/BroadcastTitle.tsx
Labels: :sparkles: Feat, FE

#206 [Feat] 방송 중인 캠퍼의 상세 정보 요청 구현
  apps/client/src/components/LiveCamperInfo.tsx
  apps/client/src/hooks/useAPI.ts
  apps/client/src/pages/Live.tsx
  apps/client/src/types/liveTypes.ts
Labels: :sparkles: Feat, FE

#210 [Fix] 방송 리스트 요청 안함 & 송출 에러 처리 해결
  apps/client/src/components/LiveList.tsx
  apps/client/src/hooks/useConsumer.ts
  apps/client/src/hooks/useMediaControls.ts
  apps/client/src/hooks/useMediaStream.ts
  apps/client/src/hooks/useProducer.ts
  apps/client/src/hooks/useRoom.ts
  apps/client/src/hooks/useSocket.ts
  apps/client/src/pages/Home.tsx
  apps/client/src/types/homeTypes.ts
Labels: :bug: Fix, FE

#211 [Feat] 채팅 UI 구현
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/src/components/ChatContainer.tsx
  apps/client/src/components/icons/SendIcon.tsx
  apps/client/src/components/icons/SmileIcon.tsx
  apps/client/src/components/ui/card.tsx
  apps/client/src/components/ui/input.tsx
  apps/client/src/components/ui/scroll-area.tsx
  apps/client/src/pages/Live.tsx
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#214 [Feat] record 서버 썸네일 저장 구현
  .github/workflows/media-deploy.yml
  .github/workflows/record-deploy.yml
  apps/media/src/sfu/services/record.service.ts
  apps/media/src/sfu/services/transport.service.ts
  apps/media/src/sfu/sfu.module.ts
  apps/media/src/sfu/sfu.service.ts
  apps/media/src/sfu/tranposrt.config.ts
  apps/record/.gitignore
  apps/record/package.json
  apps/record/src/ffmpeg.ts
  apps/record/src/index.ts
  apps/record/src/port.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#224 [Fix] chat 서버 createRoom 방식 변경 및 로거 추가
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/dto/creat-room.dto.ts
Labels: :bug: Fix, BE

#219 [Feat] 썸네일 db 저장 로직 구현
  .github/workflows/media-deploy.yml
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/broadcast/dto/createBroadcast.dto.ts
  apps/media/.env.example
  apps/media/src/broadcast/dto/createBroadcast.dto.ts
  apps/media/src/sfu/services/record.service.ts
  apps/media/src/sfu/sfu.service.ts
  apps/record/src/index.ts
Labels: :sparkles: Feat, BE

#217 [Feat] 소켓 연결 해제 이벤트 등록
  apps/media/src/attendance/attendance.module.ts
  apps/media/src/member/member.module.ts
  apps/media/src/sfu/services/client.service.ts
  apps/media/src/sfu/services/transport.service.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.module.ts
  apps/media/src/sfu/sfu.service.ts
Labels: :sparkles: Feat, BE

#226 :sparkles: [Feat]: 방송 종료 시 record 서버 리소스 정리 구현
  apps/media/src/sfu/services/record.service.ts
  apps/record/src/index.ts
Labels: :sparkles: Feat, BE

#223 :bug: [Fix]: unhandled rejection 문제 해결
  apps/media/src/common/filter/webSocketException.filter.ts
  apps/media/src/main.ts
Labels: :bug: Fix, BE

#227 [Feat] 채팅 전송/수신 로직 구현
  .github/workflows/front-deploy.yml
  apps/client/src/components/ChatContainer.tsx
  apps/client/src/components/LiveCamperInfo.tsx
  apps/client/src/env.d.ts
  apps/client/src/hooks/useSocket.ts
  apps/client/src/index.css
  apps/client/src/pages/Broadcast.tsx
  apps/client/src/pages/Live.tsx
Labels: :sparkles: Feat, FE

#230 [Feat] chat 이름 오류 수정 및 소켓 종료 로직 구현
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/client.ts
Labels: :sparkles: Feat, BE

#228 [Fix] Record 배포 스크립트 수정
  .github/workflows/media-deploy.yml
  .github/workflows/record-deploy.yml
  apps/media/.env.example
  apps/media/Dockerfile
  apps/media/src/sfu/services/record.service.ts
  apps/media/src/sfu/sfu.service.ts
  apps/record/Dockerfile
  apps/record/src/ffmpeg.ts
  apps/record/src/index.ts
Labels: :globe_with_meridians: Ci, BE

#233 [Fix] 채팅 입력 이슈 및 CSS 수정
  apps/client/index.html
  apps/client/public/favicon.ico
  apps/client/src/App.css
  apps/client/src/App.tsx
  apps/client/src/components/ChatContainer.tsx
  apps/client/src/components/LiveCamperInfo.tsx
  apps/client/src/components/LivePlayer.tsx
  apps/client/src/components/common/Header.tsx
  apps/client/src/components/ui/card.tsx
  apps/client/src/index.css
  apps/client/src/pages/Broadcast.tsx
  apps/client/src/pages/Home.tsx
  apps/client/src/pages/Live.tsx
Labels: :bug: Fix, FE

#236 [Fix] 실시간 방송 썸네일 시간 간격 조정
  apps/record/src/ffmpeg.ts
Labels: :bug: Fix, BE

#238 [Feat] 채팅창 자동 스크롤 구현 및 아래서 부터 올라오도록 수정
  apps/client/src/components/ChatContainer.tsx
Labels: :sparkles: Feat, FE

#241 [Fix] svg 이미지를 svgr 대신 컴포넌트로 만들어서 사용하도록 변경
  apps/client/package.json
  apps/client/src/assets/logo/camon_character_88.svg
  apps/client/src/assets/logo/camon_logo.svg
  apps/client/src/components/common/Header.tsx
  apps/client/src/components/icons/Character.tsx
  apps/client/src/components/icons/Logo.tsx
  apps/client/vite.config.ts
  pnpm-lock.yaml
Labels: :bug: Fix, FE

#247 [Refactor] 프론트엔드 디렉토리 구조, 아이콘, 로딩 리팩토링 및 수정
  apps/client/src/App.tsx
  apps/client/src/Router.tsx
  apps/client/src/components/ChatContainer/index.tsx
  apps/client/src/components/ErrorCharacter/index.tsx
  apps/client/src/components/Header/index.tsx
  apps/client/src/components/IconButton/index.tsx
  apps/client/src/components/LoadingCharacter/index.tsx
  apps/client/src/components/icons/index.tsx
  apps/client/src/components/ui/avatar.tsx
  apps/client/src/components/ui/badge.tsx
  apps/client/src/components/ui/button.tsx
  apps/client/src/components/ui/card.tsx
  apps/client/src/components/ui/input.tsx
  apps/client/src/components/ui/scroll-area.tsx
  apps/client/src/components/ui/select.tsx
  apps/client/src/hooks/useAPI.ts
  apps/client/src/hooks/useConsumer.ts
  apps/client/src/hooks/useProducer.ts
  apps/client/src/hooks/useTransport.ts
  apps/client/src/pages/Broadcast/BroadcastTitle.tsx
  apps/client/src/pages/Broadcast/index.tsx
  apps/client/src/pages/Home/LiveCard.tsx
  apps/client/src/pages/Home/LiveList.tsx
  apps/client/src/pages/Home/index.tsx
  apps/client/src/pages/Live/LiveCamperInfo.tsx
  apps/client/src/pages/Live/LivePlayer.tsx
  apps/client/src/pages/Live/index.tsx
  apps/client/src/pages/Profile/index.tsx
  apps/client/src/types/mediasoupTypes.ts
  apps/client/src/utils/utils.ts
  apps/client/tsconfig.json
  apps/client/vite.config.ts
Labels: :recycle: Refactor, FE

#244 [Feat]: 썸네일 삭제 로직 추가
  apps/media/src/sfu/services/record.service.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/record/src/ffmpeg.ts
  apps/record/src/index.ts
Labels: :recycle: Refactor, :sparkles: Feat, BE

#246 :sparkles: [Feat]: 채팅방 종료 알림 구현
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/client.ts
Labels: :sparkles: Feat, BE

#249 [Fix] 아이콘 export 파일 수정
  apps/client/src/components/icons/index.ts
  apps/client/src/components/icons/index.tsx
Labels: :bug: Fix, FE

#253 ⚡️ [Feat] 검색 api 구현 및 방송 리스트 api에 필터링 기능 추가
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/broadcast/dto/broadcast-list-response.dto.ts
  apps/api/src/broadcast/dto/broadcast-search-response.dto.ts
  apps/api/src/common/responses/exceptions/errorStatus.ts
Labels: :sparkles: Feat, BE

#251 [Feat] OAuth 로그인 (github, google) 구현
  .github/workflows/api-deploy.yml
  apps/api/.env.example
  apps/api/Dockerfile
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/attendance/attendance.module.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/dto/signin-response.dto.ts
  apps/api/src/auth/dto/signin.dto.ts
  apps/api/src/auth/guard/github-auth.guard.ts
  apps/api/src/auth/guard/google-auth.guard.ts
  apps/api/src/auth/guard/jwt-auth.guard.ts
  apps/api/src/auth/interface/payload.interface.ts
  apps/api/src/auth/strategy/github-auth.strategy.ts
  apps/api/src/auth/strategy/google-auth.startegy.ts
  apps/api/src/auth/strategy/jwt-auth.strategy.ts
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.module.ts
  apps/api/src/common/decorators/user-req.decorator.ts
  apps/api/src/common/responses/exceptions/errorStatus.ts
  apps/api/src/member/member.module.ts
  apps/api/src/member/member.service.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#255 [Feat] 개인 정보 수정 API 구현
  apps/api/src/common/pipe/custom-validation.pipe.ts
  apps/api/src/config/swagger.config.ts
  apps/api/src/member/dto/update-member-info.dto.ts
  apps/api/src/member/member.controller.ts
  apps/api/src/member/member.module.ts
  apps/api/src/member/member.service.ts
Labels: :sparkles: Feat, BE

#265 [Feat] 기존 방송 제목 변경 api에 jwtguard 로직 추가
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.service.ts
Labels: :sparkles: Feat, BE

#259 [Feat] 미디어서버 화질 조정 이벤트 구현
  apps/media/src/sfu/constants/quality-layer.constant.ts
  apps/media/src/sfu/dto/set-video-quality.dto.ts
  apps/media/src/sfu/services/consumer.service.ts
  apps/media/src/sfu/services/record.service.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
Labels: :sparkles: Feat, BE

#263 [Feat] 출결 조회 api 구현
  apps/api/src/member/dto/attendance-response.dto.ts
  apps/api/src/member/dto/update-member-info.dto.ts
  apps/api/src/member/member.controller.ts
  apps/api/src/member/member.module.ts
  apps/api/src/member/member.service.ts
Labels: :sparkles: Feat, BE

#266 [Feat] 방송 리스트 무한 스크롤 페이지네이션 구현
  apps/api/src/broadcast/broadcast.controller.ts
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/broadcast/dto/broadcast-list-response.dto.ts
  apps/api/src/broadcast/dto/broadcast-list.dto.ts
  apps/client/src/pages/Home/index.tsx
  apps/client/src/types/homeTypes.ts
Labels: :sparkles: Feat, BE

#270 [Fix] Live interface export 수정 및 스크립트 환경변수 수정
  .github/workflows/chat-deploy.yml
  apps/chat/Dockerfile
  apps/client/src/types/homeTypes.ts
Labels: :bug: Fix, FE, BE

#272 [Fix] 프론트엔드 배포 문제 수정
  apps/client/src/components/icons/ChatIcon.tsx
  apps/client/src/components/icons/index.ts
Labels: :construction: Build, FE

#271 [Feat] 화면 공유 구현
  apps/client/src/hooks/useProducer.ts
  apps/client/src/pages/Broadcast/BroadcastPlayer.tsx
  apps/client/src/pages/Broadcast/index.tsx
  apps/client/src/types/mediasoupTypes.ts
Labels: :sparkles: Feat, FE

#276 [Feat]: 녹화 시작 로직 구현
  .github/workflows/api-deploy.yml
  .github/workflows/chat-deploy.yml
  .github/workflows/media-deploy.yml
  .github/workflows/record-deploy.yml
  apps/media/src/sfu/services/record.service.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
  apps/record/.gitignore
  apps/record/Dockerfile
  apps/record/package.json
  apps/record/src/ffmpeg.ts
  apps/record/src/index.ts
  apps/record/test.html
  docker-compose.yml
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#280 [Ci] Docker compose 적용
  .github/workflows/api-deploy.yml
  .github/workflows/chat-deploy.yml
  .github/workflows/media-deploy.yml
  .github/workflows/record-deploy.yml
  apps/api/Dockerfile
  apps/api/src/auth/auth.controller.ts
  docker-compose.yml
Labels: :globe_with_meridians: Ci

#281 [Refactor] 코드 개선 및 클라우드 업로드 로직 구현
  .github/workflows/record-deploy.yml
  apps/media/src/sfu/services/record.service.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
  apps/record/.env.example
  apps/record/Dockerfile
  apps/record/package.json
  apps/record/src/ffmpeg.ts
  apps/record/src/index.ts
  apps/record/src/object.ts
  apps/record/test.html
  docker-compose.yml
  pnpm-lock.yaml
Labels: :recycle: Refactor, BE

#261 [Fix]: 방송 시작 조건 추가
  .github/workflows/media-deploy.yml
  apps/api/src/attendance/attendance.module.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/broadcast/broadcast.module.ts
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/common/responses/exceptions/errorStatus.ts
  apps/api/src/member/member.module.ts
  apps/media/.env.example
  apps/media/Dockerfile
  apps/media/package.json
  apps/media/src/app.module.ts
  apps/media/src/auth/auth.module.ts
  apps/media/src/auth/jwt-auth.guard.ts
  apps/media/src/auth/jwt-auth.strategy.ts
  apps/media/src/auth/payload.interface.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
  apps/media/src/types/socket.d.ts
  apps/media/src/types/user.ts
  pnpm-lock.yaml
Labels: :bug: Fix, BE

#268 [Feat] 로그인 여부에 따른 chat 이벤트 조건 추가
  apps/chat/.env.example
  apps/chat/package.json
  apps/chat/src/auth/ payload.interface.ts
  apps/chat/src/auth/auth.module.ts
  apps/chat/src/auth/jwt-auth.guard.ts
  apps/chat/src/auth/jwt-auth.strategy.ts
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.module.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/common/responses/exceptions/errorStatus.ts
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#285 [Feat] socket과 axios 요청 시 헤더에 accessToken 넣기
  apps/client/src/hooks/useSocket.ts
  apps/client/src/services/axios.ts
Labels: :sparkles: Feat, FE

#287 [Fix] 소켓에 accessToken 전달하는 방법 수정
  apps/client/src/hooks/useSocket.ts
Labels: :bug: Fix, FE

#288 [Feat] 녹화 버튼 UI & 로직 구현
  apps/client/src/components/Header/index.tsx
  apps/client/src/components/Modal/index.tsx
  apps/client/src/index.css
  apps/client/src/pages/Broadcast/RecordButton.tsx
  apps/client/src/pages/Broadcast/index.tsx
  apps/client/tailwind.config.js
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#289 [Feat] 녹화 영상 스토리지 업로드
  apps/api/src/attendance/attendance.entity.ts
  apps/api/src/attendance/attendance.module.ts
  apps/api/src/attendance/attendance.service.ts
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/record/record.entity.ts
  apps/api/src/record/record.module.ts
  apps/api/src/record/record.service.ts
  apps/chat/src/auth/jwt-auth.guard.ts
  apps/media/src/auth/jwt-auth.guard.ts
  apps/media/src/sfu/services/record.service.ts
  apps/media/src/sfu/sfu.gateway.ts
  apps/media/src/sfu/sfu.service.ts
  apps/record/src/ffmpeg.ts
  apps/record/src/index.ts
  apps/record/src/object.ts
  apps/record/src/port.ts
Labels: :sparkles: Feat, BE

#292 [Fix] 불필요한 Promise & try-catch 삭제 및 화면 공유 중단 시 처리 추가
  apps/chat/src/auth/jwt-auth.strategy.ts
  apps/client/src/components/Icons/BlogIcon.tsx
  apps/client/src/components/Icons/CloseIcon.tsx
  apps/client/src/components/Icons/EditIcon.tsx
  apps/client/src/components/Icons/ExpandIcon.tsx
  apps/client/src/components/Icons/MailIcon.tsx
  apps/client/src/components/Icons/MicrophoneOffIcon.tsx
  apps/client/src/components/Icons/MicrophoneOnIcon.tsx
  apps/client/src/components/Icons/MonitorShareIcon.tsx
  apps/client/src/components/Icons/PauseIcon.tsx
  apps/client/src/components/Icons/PlayIcon.tsx
  apps/client/src/components/Icons/ScreenShareIcon.tsx
  apps/client/src/components/Icons/ScreenShareOffIcon.tsx
  apps/client/src/components/Icons/SmileIcon.tsx
  apps/client/src/components/Icons/VideoOffIcon.tsx
  apps/client/src/components/Icons/VideoOnIcon.tsx
  apps/client/src/components/Icons/VolumeOffIcon.tsx
  apps/client/src/components/Icons/VolumeOnIcon.tsx
  apps/client/src/components/Icons/index.ts
  apps/client/src/hooks/useConsumer.ts
  apps/client/src/hooks/useProducer.ts
  apps/client/src/hooks/useRoom.ts
  apps/client/src/hooks/useScreenShare.ts
  apps/client/src/hooks/useTransport.ts
  apps/client/src/pages/Broadcast/index.tsx
Labels: :bug: Fix, FE

#297 [Fix] 출석 response dto 응답 데이터 수정
  apps/api/src/member/dto/attendance-response.dto.ts
  docker-compose.yml
Labels: :bug: Fix, BE

#300 [Feat] 녹화 영상 조회 api 구현
  .github/workflows/record-deploy.yml
  apps/api/.env.example
  apps/api/src/app.module.ts
  apps/api/src/common/responses/exceptions/errorStatus.ts
  apps/api/src/record/dto/create-record.dto.ts
  apps/api/src/record/dto/records-response.dto.ts
  apps/api/src/record/dto/update-record.dto.ts
  apps/api/src/record/record.controller.ts
  apps/api/src/record/record.entity.ts
  apps/api/src/record/record.module.ts
  apps/api/src/record/record.service.ts
  apps/media/src/auth/jwt-auth.guard.ts
  apps/media/src/sfu/services/record.service.ts
  apps/record/.env.example
  apps/record/Dockerfile
  apps/record/package.json
  apps/record/src/object.ts
  docker-compose.yml
  pnpm-lock.yaml
Labels: :sparkles: Feat, BE

#291 [Feat] 방송 화질 조정 기능 구현
  apps/client/src/constants/videoOptions.ts
  apps/client/src/hooks/useProducer.ts
  apps/client/src/pages/Broadcast/BroadcastPlayer.tsx
  apps/client/src/pages/Live/LivePlayer.tsx
  apps/client/src/pages/Live/index.tsx
  apps/client/tsconfig.json
Labels: :sparkles: Feat, FE

#301 [Fix] canvas 잘못된 변수 주입 수정
  apps/client/src/pages/Broadcast/BroadcastPlayer.tsx
Labels: :bug: Fix, FE

#302 [Fix] 로그인 2번 눌러야 헤더에 반영되는 문제 수정
  apps/client/src/App.tsx
  apps/client/src/components/Header/index.tsx
  apps/client/src/contexts/AuthContext.tsx
  apps/client/src/hooks/useAuth.ts
  apps/client/src/pages/Auth/index.tsx
Labels: :bug: Fix, FE

#294 [Feat] Record 페이지 구현
  apps/client/package.json
  apps/client/src/Router.tsx
  apps/client/src/pages/Record/RecordInfo.tsx
  apps/client/src/pages/Record/RecordList.tsx
  apps/client/src/pages/Record/RecordPlayer.tsx
  apps/client/src/pages/Record/index.tsx
  pnpm-lock.yaml
Labels: :sparkles: Feat, FE

#304 [Fix] 녹화 영상 보기 화면으로 이동 구현
  apps/client/src/pages/Profile/Attendance.tsx
Labels: :bug: Fix, FE

#306 :bug: [Fix]: 디렉토리 삭제 코드 제거
  apps/record/src/ffmpeg.ts
Labels: :bug: Fix, BE

#308 :bug: [Fix]: dto 수정
  apps/api/src/member/dto/attendance-response.dto.ts
Labels: :bug: Fix, BE

#309 :bug: [Fix]: dto 수정
  apps/api/src/member/dto/attendance-response.dto.ts
Labels: :bug: Fix, BE

#313 :bug: [Fix]: 방송 조회 API 수정
  apps/api/src/broadcast/broadcast.service.ts
  apps/api/src/broadcast/dto/broadcast-list.dto.ts
Labels: :bug: Fix, BE
