Repository boostcampwm-2024/web20-camon, pull requests merged in 2024-12, with the labels that each got.

#318 [Feat] 분야별 필터링 구현
  apps/client/src/pages/Home/FieldFilter.tsx
  apps/client/src/pages/Home/LiveList.tsx
  apps/client/src/pages/Home/Search.tsx
  apps/client/src/pages/Home/index.tsx
  apps/client/src/types/liveTypes.ts
Labels: :sparkles: Feat, FE

#322 [Feat] 검색 UI & 로직 구현
  apps/client/src/components/Header/index.tsx
  apps/client/src/components/Icons/SearchIcon.tsx
  apps/client/src/components/Icons/index.ts
  apps/client/src/pages/Home/FieldFilter.tsx
  apps/client/src/pages/Home/LiveList.tsx
  apps/client/src/pages/Home/Search.tsx
Labels: :sparkles: Feat, FE

#320 [Docs] readme 수정
  README.md
Labels: :memo: Docs

#323 [Feat] 배너 북마크 CRD api 구현
  apps/api/src/app.module.ts
  apps/api/src/bookmark/bookmark.controller.ts
  apps/api/src/bookmark/bookmark.entity.ts
  apps/api/src/bookmark/bookmark.module.ts
  apps/api/src/bookmark/bookmark.service.ts
  apps/api/src/bookmark/dto/bookmark-list-response.dto.ts
  apps/api/src/bookmark/dto/create-bookmark.dto.ts
  apps/api/src/common/responses/exceptions/errorStatus.ts
Labels: :sparkles: Feat, BE

#325 [Fix] api 스웨거 설정
  apps/api/src/bookmark/bookmark.controller.ts
  apps/api/src/bookmark/dto/create-bookmark-response.dto.ts
  apps/api/src/bookmark/dto/create-bookmark.dto.ts
Labels: :bug: Fix, BE

#317 [Fix] 방송 제목 null로 들어가는 이슈 해결 및 도커 이미지 빌드 시간 단축
  .github/workflows/media-deploy.yml
  apps/media/src/app.module.ts
  apps/media/src/auth/auth.module.ts
  apps/media/src/auth/jwt-auth.guard.ts
  apps/media/src/auth/jwt-auth.strategy.ts
  apps/media/src/auth/payload.interface.ts
  apps/media/src/common/clients/api-client.interface.ts
  apps/media/src/common/clients/api.client.ts
  apps/media/src/member/member.module.ts
  apps/media/src/member/member.service.ts
  docker-compose.yml
Labels: :bug: Fix, :globe_with_meridians: Ci, BE

#324 [Feat] 내 정보 수정 UI & 로직 구현
  apps/client/src/pages/Live/LiveCamperInfo.tsx
  apps/client/src/pages/Profile/EditUserInfo.tsx
  apps/client/src/pages/Profile/UserInfo.tsx
  apps/client/src/pages/Profile/index.tsx
Labels: :sparkles: Feat, FE

#327 [Feat] 배너 & 북마크 구현
  apps/client/package-lock.json
  apps/client/package.json
  apps/client/public/images/camon_character_200.png
  apps/client/src/App.tsx
  apps/client/src/components/ui/toast.tsx
  apps/client/src/components/ui/toaster.tsx
  apps/client/src/hooks/useToast.ts
  apps/client/src/pages/Home/Banner.tsx
  apps/client/src/pages/Home/index.tsx
  apps/client/tailwind.config.js
Labels: :sparkles: Feat, FE

#333 [Fix]: 배너 css(margin, gap) 수정
  apps/client/src/components/Icons/MoveCharacter.tsx
  apps/client/src/pages/Home/Banner.tsx
  pnpm-lock.yaml
Labels: :bug: Fix, FE

#331 [Fix] 방송 검색 빈 keyword 입력 시, 전체 방송리스트 반환
  apps/api/src/broadcast/broadcast.service.ts
Labels: :bug: Fix, BE

#337 [Feat] 로그인 시 필수 정보 없을 경우 redirect url 수정
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/member/dto/update-member-info.dto.ts
Labels: :sparkles: Feat, BE

#339 [Feat] member 데이터 확인 조건문 수정
  apps/api/src/auth/auth.service.ts
Labels: :sparkles: Feat, BE

#340 :bug: [Fix]: 로그인 시 isNecessaryInfo 확인 수정
  apps/client/src/pages/Auth/index.tsx
Labels: :bug: Fix, FE

#344 [Fix] 최초 로그인 시 개인 정보 페이지가 편집 모드로 전환
  apps/client/src/components/Header/index.tsx
  apps/client/src/pages/Home/Banner.tsx
  apps/client/src/pages/Profile/UserInfo.tsx
  apps/client/src/pages/Profile/index.tsx
Labels: :bug: Fix, FE

#348 [Feat] 로그인 여부에 따른 접근 제한 처리 및 기타 리팩토링
  apps/client/src/ProtectedRoute.tsx
  apps/client/src/Router.tsx
  apps/client/src/components/ChatContainer/index.tsx
  apps/client/src/pages/Auth/index.tsx
  apps/client/src/pages/Broadcast/index.tsx
  apps/client/src/pages/Home/Banner.tsx
  apps/client/src/pages/Home/Bookmark.tsx
  apps/client/src/pages/Live/LivePlayer.tsx
  apps/client/src/pages/Live/index.tsx
  apps/client/src/pages/Profile/Attendance.tsx
  apps/client/src/pages/Profile/UserInfo.tsx
  apps/client/src/pages/Record/RecordList.tsx
  apps/client/src/pages/Record/index.tsx
Labels: :bug: Fix, :recycle: Refactor, :sparkles: Feat, FE

#350 [Fix] 빌드 실패 원인 해결
  apps/client/src/Router.tsx
  apps/client/src/pages/Profile/index.tsx
Labels: :bug: Fix, FE

#342 [Fix] 로그인 구현에 따른, createRoom 및 joinRoom 이벤트 수정
  .github/workflows/chat-deploy.yml
  apps/chat/.env.example
  apps/chat/.eslintrc.js
  apps/chat/Dockerfile
  apps/chat/package.json
  apps/chat/src/app.module.ts
  apps/chat/src/auth/jwt-auth.guard.ts
  apps/chat/src/auth/jwt-auth.strategy.ts
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.module.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/dto/creat-room.dto.ts
  apps/chat/src/chat/dto/join-room.dto.ts
  apps/chat/src/common/clients/api-client.interface.ts
  apps/chat/src/common/clients/api.client.ts
  apps/chat/src/common/responses/exceptions/errorStatus.ts
  apps/chat/src/config/configuration.ts
  apps/chat/src/member/interfaces/member-service.interface.ts
  apps/chat/src/member/interfaces/member.interface.ts
  apps/chat/src/member/member.module.ts
  apps/chat/src/member/member.service.ts
  apps/chat/src/types/socket.d.ts
  docker-compose.yml
  pnpm-lock.yaml
Labels: :bug: Fix, BE

#346 [Fix] 썸네일 기본 이미지 설정
  apps/media/src/common/clients/record-client.interface.ts
  apps/media/src/common/clients/record.client.ts
  apps/media/src/common/responses/exceptions/errorStatus.ts
  apps/media/src/sfu/sfu.module.ts
  apps/media/src/sfu/sfu.service.ts
  apps/record/Dockerfile
  apps/record/public/default-thumbnail.jpg
  apps/record/src/ffmpeg.ts
  apps/record/src/index.ts
Labels: :bug: Fix, BE

#353 [Feat] 방송 목록 무한 스크롤
  apps/client/src/App.tsx
  apps/client/src/components/Footer/index.tsx
  apps/client/src/hooks/useIntersect.ts
  apps/client/src/main.tsx
  apps/client/src/pages/Home/FieldFilter.tsx
  apps/client/src/pages/Home/LiveList.tsx
  apps/client/src/pages/Home/index.tsx
  apps/client/src/types/homeTypes.ts
Labels: :sparkles: Feat, FE

#352 [Fix]: 채팅방 입장 수정
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.service.ts
Labels: :bug: Fix, BE

#355 [Design] 채팅 높이 수정
  apps/client/src/App.css
Labels: :lipstick: Design, FE

#356 :bug: [Fix]: 토큰 없어도 채팅방 입장 가능하게 수정
  apps/chat/src/chat/chat.service.ts
Labels: :bug: Fix, BE

#357 [Design] 푸터 삭제 & 시청 페이지 하단 패딩 추가
  apps/client/src/pages/Home/index.tsx
  apps/client/src/pages/Live/index.tsx
Labels: :lipstick: Design, FE

#361 [Design] 방송 목록 CSS 수정 & 배너 애니메이션 추가
  apps/client/src/pages/Home/Banner.tsx
  apps/client/src/pages/Home/LiveList.tsx
  apps/client/src/pages/Home/index.tsx
  apps/client/tailwind.config.js
Labels: :lipstick: Design, FE

#363 [Feat] 게스트 로그인 구현
  apps/client/src/components/Header/LogInButton.tsx
  apps/client/src/components/Header/index.tsx
Labels: :sparkles: Feat, FE

#368 [Fix] ffmpeg 옵션 수정
  apps/record/src/ffmpeg.ts
Labels: :bug: Fix, BE

#369 [Fix]: 출석부 반환 시 utc+9 반환
  apps/api/src/member/dto/attendance-response.dto.ts
Labels: :bug: Fix, BE

#372 [Feat] 방송 종료 알림 모달 구현
  apps/client/src/components/ChatContainer/ChatEndModal.tsx
  apps/client/src/components/ChatContainer/index.tsx
Labels: :sparkles: Feat, FE

#373 [Fix]: 녹화 로직 개선
  apps/api/src/common/responses/exceptions/errorStatus.ts
  apps/api/src/record/record.service.ts
  apps/record/src/exchage.ts
  apps/record/src/ffmpeg.ts
  apps/record/src/index.ts
  apps/record/src/object.ts
  apps/record/src/queue.ts
Labels: :bug: Fix, BE

#374 [Fix] 캔버스 사용으로 인한 클라이언트 부하 문제 해결
  apps/client/src/hooks/useMedia.ts
  apps/client/src/hooks/useMediaControls.ts
  apps/client/src/hooks/useMediaStream.ts
  apps/client/src/hooks/useProducer.ts
  apps/client/src/pages/Broadcast/BroadcastPlayer.tsx
  apps/client/src/pages/Broadcast/index.tsx
  apps/client/src/pages/Live/LiveCamperInfo.tsx
  apps/client/src/pages/Live/LivePlayer.tsx
  apps/client/src/pages/Live/index.tsx
Labels: :bug: Fix, FE

#376 [Refactor] 기타 리팩토링 및 수정 사항
  apps/client/src/components/ChatContainer/index.tsx
  apps/client/src/hooks/useConsumer.ts
  apps/client/src/hooks/useMedia.ts
  apps/client/src/hooks/useProducer.ts
  apps/client/src/hooks/useRoom.ts
  apps/client/src/hooks/useScreenShare.ts
  apps/client/src/hooks/useSocket.ts
  apps/client/src/hooks/useTransport.ts
  apps/client/src/pages/Broadcast/BroadcastPlayer.tsx
  apps/client/src/pages/Broadcast/RecordButton.tsx
  apps/client/src/pages/Broadcast/index.tsx
  apps/client/src/pages/Home/Bookmark.tsx
  apps/client/src/pages/Live/LivePlayer.tsx
  apps/client/src/pages/Profile/Attendance.tsx
  apps/client/src/pages/Profile/EditUserInfo.tsx
  apps/client/src/pages/Profile/index.tsx
Labels: :bug: Fix, :recycle: Refactor, :sparkles: Feat, FE

#378 [Fix] getUserMedia에서 비디오 옵션 수정
  apps/client/src/hooks/useMedia.ts
  apps/media/src/sfu/services/consumer.service.ts
  apps/media/src/sfu/services/record.service.ts
Labels: :bug: Fix, FE
